apiVersion: v1
kind: PersistentVolume
metadata:
  name: expense-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc    # must match PVC
  hostPath:
    path: /run/desktop/mnt/host/c/Users/asus/resume-maj-project/multi-tenant-saas/data/expense-db
    type: DirectoryOrCreate
  claimRef:
    namespace: tenant-b
    name: expense-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: expense-pvc
  namespace: tenant-b
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ebs-sc
