apiVersion: v1
kind: PersistentVolume
metadata:
  name: notes-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc    # must match PVC
  hostPath:
    path: /run/desktop/mnt/host/c/Users/asus/resume-maj-project/multi-tenant-saas/data/notes-db
    type: DirectoryOrCreate
  claimRef:
    namespace: tenant-a
    name: notes-pvc
 

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notes-pvc
  namespace: tenant-a
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ebs-sc

