global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "mock_cost_exporter"
    static_configs:
      - targets: ["mock_cost_exporter:8000"]

  - job_name: "aws_exporter"
    static_configs:
      - targets: ["aws_exporter:8001"]
