apiVersion: v1
kind: Service
metadata:
  name: notes-service
  namespace: tenant-a
spec:
  selector:
    app: notes-app
  ports:
    - protocol: TCP
      port: 5000        # Cluster port
      targetPort: 5000  # Pod container port
  type: ClusterIP       # internal access within cluster
