apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-deployment
  namespace: tenant-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      containers:
      - name: notes-app
        image: notes-app:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "128Mi"
        volumeMounts:
        - name: notes-db-storage
          mountPath: /app/db
      volumes:
      - name: notes-db-storage
        persistentVolumeClaim:
          claimName: notes-pvc
