name: Deploy Fortune Cookie App

on:
  push:
    branches:
      - Folder-1         # Change to your branch
    paths:
      - 'app/**'  # Folder containing Dockerfile

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Configure AWS CLI
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1   # or your region

      # 3️⃣ Login to ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO_URI }}

      # 4️⃣ Build and tag Docker image
      - name: Build Docker image
        run: |
          IMAGE_TAG="${GITHUB_SHA::7}"
          docker build -t fortune-cookie:latest ./app
          docker tag fortune-cookie:latest ${{ secrets.ECR_REPO_URI }}:${IMAGE_TAG}

      # 5️⃣ Push Docker image to ECR
      - name: Push Docker image
        run: |
          IMAGE_TAG="${GITHUB_SHA::7}"
          docker push ${{ secrets.ECR_REPO_URI }}:${IMAGE_TAG}

      # 6️⃣ Deploy on EC2 using SSM
      - name: Deploy to EC2
        run: |
          # Get EC2 instance ID dynamically using tag
          INSTANCE_ID=$(aws ec2 describe-instances \
            --filters "Name=tag:Role,Values=FortuneApp" "Name=instance-state-name,Values=running" \
            --query "Reservations[].Instances[].InstanceId" --output text)

          IMAGE_TAG="${GITHUB_SHA::7}"

          # Run commands on EC2 via SSM as a JSON array
          aws ssm send-command \
            --targets "Key=instanceIds,Values=$INSTANCE_ID" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy Fortune Cookie App" \
            --parameters commands='[
              "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO_URI }}",
              "docker pull ${{ secrets.ECR_REPO_URI }}:'"${IMAGE_TAG}"'",
              "docker stop fortune-cookie || true",
              "docker rm fortune-cookie || true",
              "docker run -d -p 5000:5000 --name fortune-cookie ${{ secrets.ECR_REPO_URI }}:'"${IMAGE_TAG}"'"
            ]' \
            --region us-east-1
